### CREATE
POST http://localhost:3000/bikes/ HTTP/1.1
Content-Type: application/json

{
    "name": "Roberto",
    "brand": "BMC",
    "model": "electric bike",
    "price": 599,
    "category": "premium",
    "store": "63bed9e70c0fe97ca71a6f06"
}

### READ

# GET http://localhost:3000/bikes/ HTTP/1.1

GET http://localhost:3000/bikes/63bd98c753c865b8d0545771 HTTP/1.1

### UPDATE
PUT http://localhost:3000/bikes/63bd98c753c865b8d0545771 HTTP/1.1
Content-Type: application/json

{
    "name": "Juan"
}

### DELETE
DELETE http://localhost:3000/bikes/63bdca6faa8aa1f0c0bc5ebf HTTP/1.1






### CREATE STORE
POST http://localhost:3000/stores/ HTTP/1.1
Content-Type: application/json

{
    "name": "BiciPalma",
    "address": "Plaza espanya 32"
}


### DELETE STORE & BIKE
DELETE http://localhost:3000/stores/63bed9e70c0fe97ca71a6f06 HTTP/1.1